Repository unh-webappdev/FlashCourses_api, pull requests merged in 2018-04, with the labels that each got.

#44 Develop
  Flash_course/src/accounts/api/serializers.py
  Flash_course/src/accounts/api/urls.py
  Flash_course/src/accounts/api/views.py
  Flash_course/src/accounts/urls.py
  flash/README.md
  flash/docs/README.md
  flash/docs/requirements.txt
  flash/src/seeder.py
Labels: master baseline

#47 Develop
  flash/src/FlashCourses/settings/api_settings.py
  flash/src/FlashCourses/urls.py
  flash/src/accounts/api/serializers.py
  flash/src/accounts/api/urls.py
  flash/src/accounts/api/views.py
  flash/src/accounts/urls.py
  flash/src/flashcards/api/serializers.py
Labels: master baseline

#51 Develop
  flash/src/FlashCourse
  flash/src/FlashCourses/settings/api_settings.py
  flash/src/FlashCourses/settings/common.py
  flash/src/FlashCourses/urls.py
  flash/src/accounts/migrations/0001_initial.py
  flash/src/accounts/models.py
  flash/src/courses/api/serializers.py
  flash/src/courses/api/urls.py
  flash/src/courses/api/views.py
  flash/src/courses/migrations/0001_initial.py
  flash/src/courses/migrations/0002_course_course_title.py
  flash/src/courses/models.py
  flash/src/courses/urls.py
  flash/src/flashcards/admin.py
  flash/src/flashcards/migrations/0001_initial.py
  flash/src/flashcards/models.py
Labels: master baseline

#53 Develop
  flash/src/courses/api/serializers.py
  flash/src/courses/api/urls.py
  flash/src/courses/api/views.py
  flash/src/flashcards/api/serializers.py
  flash/src/flashcards/api/urls.py
  flash/src/flashcards/api/views.py
Labels: master baseline

#55 Update seeder.py
  README.md
  flash/src/FlashCourse
  flash/src/courses/models.py
  flash/src/flashcards/models.py
  flash/src/seeder.py
Labels: initial baseline

#56 Develop
  README.md
  flash/src/FlashCourse
  flash/src/courses/models.py
  flash/src/flashcards/models.py
  flash/src/seeder.py
Labels: master baseline

#57 api.md - installation instructions (rework)
  flash/docs/api.md
Labels: documentation

#61 Changes to courses, flashcards, and accounts APIs, etc.
  flash/src/accounts/api/serializers.py
  flash/src/courses/api/serializers.py
  flash/src/courses/api/urls.py
  flash/src/courses/api/views.py
  flash/src/flashcards/api/serializers.py
  flash/src/flashcards/api/urls.py
  flash/src/flashcards/api/views.py
Labels: initial baseline

#63 Develop
  flash/src/FlashCourses/db.sqlite3
  flash/src/accounts/api/serializers.py
  flash/src/courses/api/serializers.py
  flash/src/courses/api/urls.py
  flash/src/courses/api/views.py
  flash/src/courses/models.py
  flash/src/flashcards/api/serializers.py
  flash/src/flashcards/api/urls.py
  flash/src/flashcards/api/views.py
  flash/src/flashcards/models.py
Labels: master baseline

#66 Hot Fix for Database/API Issues on 4/17/2018
  flash/src/courses/api/serializers.py
  flash/src/courses/models.py
  flash/src/flashcards/api/serializers.py
Labels: initial baseline

#67 Develop
  flash/src/FlashCourses/db.sqlite3
  flash/src/courses/api/serializers.py
  flash/src/courses/models.py
  flash/src/flashcards/api/serializers.py
Labels: master baseline

#72 Update Seeder.py and Docstrings Headers
  flash/src/FlashCourses/settings/common.py
  flash/src/FlashCourses/wsgi.py
  flash/src/accounts/models.py
  flash/src/courses/models.py
  flash/src/flashcards/models.py
  flash/src/manage.py
  flash/src/seeder.py
Labels: initial baseline

#73 Develop
  flash/src/FlashCourses/settings/api_settings.py
  flash/src/FlashCourses/settings/common.py
  flash/src/FlashCourses/wsgi.py
  flash/src/accounts/api/serializers.py
  flash/src/accounts/api/urls.py
  flash/src/accounts/api/views.py
  flash/src/accounts/models.py
  flash/src/courses/api/serializers.py
  flash/src/courses/api/views.py
  flash/src/courses/models.py
  flash/src/flashcards/api/serializers.py
  flash/src/flashcards/api/views.py
  flash/src/flashcards/models.py
  flash/src/manage.py
  flash/src/seeder.py
Labels: master baseline

#74 Added Object Level Permissions to API Endpoints
  flash/src/FlashCourses/settings/api_settings.py
  flash/src/courses/api/views.py
  flash/src/flashcards/api/permissions.py
  flash/src/flashcards/api/views.py
Labels: initial baseline

#75 Develop
  flash/src/FlashCourses/settings/api_settings.py
  flash/src/courses/api/views.py
  flash/src/flashcards/api/permissions.py
  flash/src/flashcards/api/views.py
Labels: master baseline

#78 Update Headers and Documentation
  README.md
  flash/README.md
  flash/src/FlashCourses/settings/common.py
  flash/src/README.md
  flash/src/accounts/admin.py
  flash/src/accounts/apps.py
  flash/src/courses/admin.py
  flash/src/courses/apps.py
  flash/src/flashcards/admin.py
  flash/src/flashcards/apps.py
  flash/src/seeder.py
Labels: documentation, initial baseline
